name: Sample Book App Workflow

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build-docker-image:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/build
  deploy-dev:
    runs-on: self-hosted
    needs: [build-docker-image]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/deploy
        with:
          environment: 'dev'
  test-dev:
    runs-on: self-hosted
    needs: [deploy-dev]
    steps:
      - uses: ./.github/actions/test
        with:
          environment: 'DEV'
  deploy-stg:
    runs-on: self-hosted
    needs: [test-dev]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/deploy
        with:
          environment: 'stg'
  test-stg:
    runs-on: self-hosted
    needs: [deploy-stg]
    steps:
      - uses: ./.github/actions/test
        with:
          environment: 'STG'
  deploy-prd:
    runs-on: self-hosted
    needs: [test-stg]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/deploy
        with:
          environment: 'prd'
  test-prd:
    runs-on: self-hosted
    needs: [deploy-prd]
    steps:
      - uses: ./.github/actions/test
        with:
          environment: 'PRD'